#!/bin/sh
OPT=`getopt gO $*`
if [ "$?" -ne 0 ]; then
  exit 1
fi
set -- $OPT
for i; do
    case $i in
        --) break;;
        -g) opt_g=true;;
        -O) opt_O=true;;
    esac
    shift
done
shift
gosh -I ./compiler/ -l compile.scm -e "(begin (compile-file \"$1\" \"${1%.*}\") (exit))"
if [ $opt_g ]; then
    gcc -g -Wall -o ${1%.*} ${1%.*}.c -L./core -L./builtin -lbuiltin -lcore
elif [ $opt_O ]; then
    gcc -O2 -o ${1%.*} ${1%.*}.c -L./core -L./builtin -lbuiltin -lcore
else
    gcc -o ${1%.*} ${1%.*}.c -L./core -L./builtin -lbuiltin -lcore
fi
